# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile

FROM node:lts-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./
RUN npm ci
COPY src ./src
RUN npm run build

FROM node:lts-alpine
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package.json ./

ENV PORT=3000
EXPOSE 3000

CMD ["node", "dist/index.js"]
